# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(FCFCFE)
$foreground = rgb(101112)
$color0 = rgb(FFFFFF)
$color1 = rgb(6A6B70)
$color2 = rgb(717276)
$color3 = rgb(4C4D50)
$color4 = rgb(4B466F)
$color5 = rgb(202224)
$color6 = rgb(1A1C1D)
$color7 = rgb(101112)
$color8 = rgb(75767A)
$color9 = rgb(8D8F95)
$color10 = rgb(96989D)
$color11 = rgb(65676B)
$color12 = rgb(645E94)
$color13 = rgb(2B2D2F)
$color14 = rgb(232527)
$color15 = rgb(050606)
