# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #101112
background         #FCFCFE
cursor             #535457

active_tab_foreground     #FCFCFE
active_tab_background     #101112
inactive_tab_foreground   #101112
inactive_tab_background   #FCFCFE

active_border_color   #101112
inactive_border_color #FCFCFE
bell_border_color     #6A6B70

color0      #FFFFFF
color1		#6A6B70
color2		#717276
color3		#4C4D50
color4		#4B466F
color5		#202224
color6		#1A1C1D
color7		#101112
color8		#75767A
color9		#8D8F95
color10		#96989D
color11		#65676B
color12		#645E94
color13		#2B2D2F
color14		#232527
color15		#050606
